/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/hchenc/pager/pkg/apis/devops/v1alpha1"
	scheme "github.com/hchenc/pager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PagersGetter has a method to return a PagerInterface.
// A group's client should implement this interface.
type PagersGetter interface {
	Pagers(namespace string) PagerInterface
}

// PagerInterface has methods to work with Pager resources.
type PagerInterface interface {
	Create(ctx context.Context, pager *v1alpha1.Pager, opts v1.CreateOptions) (*v1alpha1.Pager, error)
	Update(ctx context.Context, pager *v1alpha1.Pager, opts v1.UpdateOptions) (*v1alpha1.Pager, error)
	UpdateStatus(ctx context.Context, pager *v1alpha1.Pager, opts v1.UpdateOptions) (*v1alpha1.Pager, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Pager, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PagerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pager, err error)
	PagerExpansion
}

// pagers implements PagerInterface
type pagers struct {
	client rest.Interface
	ns     string
}

// newPagers returns a Pagers
func newPagers(c *DevopsV1alpha1Client, namespace string) *pagers {
	return &pagers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pager, and returns the corresponding pager object, and an error if there is any.
func (c *pagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Pager, err error) {
	result = &v1alpha1.Pager{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Pagers that match those selectors.
func (c *pagers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PagerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PagerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pagers.
func (c *pagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pager and creates it.  Returns the server's representation of the pager, and an error, if there is any.
func (c *pagers) Create(ctx context.Context, pager *v1alpha1.Pager, opts v1.CreateOptions) (result *v1alpha1.Pager, err error) {
	result = &v1alpha1.Pager{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pager).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pager and updates it. Returns the server's representation of the pager, and an error, if there is any.
func (c *pagers) Update(ctx context.Context, pager *v1alpha1.Pager, opts v1.UpdateOptions) (result *v1alpha1.Pager, err error) {
	result = &v1alpha1.Pager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pagers").
		Name(pager.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pager).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pagers) UpdateStatus(ctx context.Context, pager *v1alpha1.Pager, opts v1.UpdateOptions) (result *v1alpha1.Pager, err error) {
	result = &v1alpha1.Pager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pagers").
		Name(pager.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pager).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pager and deletes it. Returns an error if one occurs.
func (c *pagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pagers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pagers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pager.
func (c *pagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pager, err error) {
	result = &v1alpha1.Pager{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pagers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
